### ISSUE TITLE
unknown "float(x,y)" and "set('s1','s2',...)"

### ISSUE THREAD

**Issue by anthalamus** [maxlapshin/mysql2postgres#12]
I got 3 types of errors when running the script on my data. Here are the descriptions:

    =========================
    1. float(x,y):
    
    error message:
    Unknown {:auto_increment=>false, :type=>"float(10,5)", :length=>10, :table_name=>"trubripes_gene_ensembl__homolog_Mdom__dm", :decimals=>"5", :null=>true, :name=>"dn_4014", :primary_key=>false}
    
    mysql:
    `dn_4014` float(10,5) DEFAULT NULL,
    --------------------------------------
    2. set('x',...):
    
    error message:
    Unknown {:auto_increment=>false, :type=>"set('SOFA','biosapiens','gosubset_prok','goslim_candida','goslim_generic','goslim_goa','goslim_pir','goslim_plant','goslim_pombe','goslim_yeast')", :length=>40, :table_name=>"acarolinensis_gene_ensembl__go_biological_process__dm", :decimals=>nil, :null=>true, :name=>"subsets_1006", :primary_key=>false}
    
    mysql:
    `subsets_1006` set('SOFA','biosapiens','gosubset_prok','goslim_candida','goslim_generic','goslim_goa','goslim_pir','goslim_plant','goslim_pombe','goslim_yeast') DEFAULT NULL,
    --------------------------------------
    3. set('x',...):
    
    error message:
    Unknown {:auto_increment=>false, :type=>"set('ESSENTIAL_SPLICE_SITE','STOP_GAINED','STOP_LOST','COMPLEX_INDEL','FRAMESHIFT_CODING','NON_SYNONYMOUS_CODING','SPLICE_SITE','PARTIAL_CODON','SYNONYMOUS_CODING','REGULATORY_REGION','WITHIN_MATURE_miRNA','5PRIME_UTR','3PRIME_UTR','INTRONIC','NMD_TRANSCRIPT','UPSTREAM','DOWNSTREAM','WITHIN_NON_CODING_GENE','NO_CONSEQUENCE','INTERGENIC')", :length=>4, :table_name=>"btaurus_gene_ensembl__transcript_variation__dm", :decimals=>nil, :null=>true, :name=>"consequence_type_2026", :default=>"INTERGENIC", :primary_key=>false}
    
    mysql:
    `consequence_type_2026` set('ESSENTIAL_SPLICE_SITE','STOP_GAINED','STOP_LOST','COMPLEX_INDEL','FRAMESHIFT_CODING','NON_SYNONYMOUS_CODING','SPLICE_SITE','PARTIAL_CODON','SYNONYMOUS_CODING','REGULATORY_REGION','WITHIN_MATURE_miRNA','5PRIME_UTR','3PRIME_UTR','INTRONIC','NMD_TRANSCRIPT','UPSTREAM','DOWNSTREAM','WITHIN_NON_CODING_GENE','NO_CONSEQUENCE','INTERGENIC') DEFAULT 'INTERGENIC',  `
    --------------------------------------

(very) quick (and ugly yet working) fix, add lines:

	    when "float(10,5)"
	      default = " DEFAULT #{column[:default].nil? ? 'NULL' : column[:default].to_f}" if default
	      "real"
	    when "set('SOFA','biosapiens','gosubset_prok','goslim_candida','goslim_generic','goslim_goa','goslim_pir','goslim_plant','goslim_pombe','goslim_yeast')"
	      default = default + "::character varying" if default
	      "character varying(#{column[:length]})"      
	    when "set('ESSENTIAL_SPLICE_SITE','STOP_GAINED','STOP_LOST','COMPLEX_INDEL','FRAMESHIFT_CODING','NON_SYNONYMOUS_CODING','SPLICE_SITE','PARTIAL_CODON','SYNONYMOUS_CODING','REGULATORY_REGION','WITHIN_MATURE_miRNA','5PRIME_UTR','3PRIME_UTR','INTRONIC','NMD_TRANSCRIPT','UPSTREAM','DOWNSTREAM','WITHIN_NON_CODING_GENE','NO_CONSEQUENCE','INTERGENIC')"
	      default = default + "::character varying" if default
	      "character varying(#{column[:length]})"

----------------------------------------
Obviously the above quick fix only works for my data, however I guess someone in desperate need of a quick fix could reuse the idea.

Being a complete ignorant in ruby, I will leave it to the experts to come up with a proper fix (with "starts_with" or regex I suppose)!

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments against the `master` branch.
