### ISSUE TITLE
Some problems while migrating a database

### ISSUE THREAD

**Issue by johbo** [maxlapshin/mysql2postgres#13]
I just did a migration from a mysql database and had some issues. I tried some simple fixes, but I must admit, that I do not speak any Ruby ;-)

So the attached diff may inspire you to find a real solution. The problems seemed to be realted to enum columns which had some default values.

    diff --git a/mysql2psql b/mysql2psql
    index 1ad9a04..a035133 100755
    --- a/mysql2psql
    +++ b/mysql2psql
    @@ -60,7 +60,7 @@

     require 'rubygems'
     require 'mysql'
    -gem "pg"
    +# gem "pg"
     require 'pg'
     require 'yaml'

    @@ -336,10 +336,10 @@ class PostgresWriter < Writer
         when "text"
           "text"
         when /^enum/
    -      default = " DEFAULT #{column[:default].nil? ? 'NULL' : column[:default]}" if default
    +      default = " DEFAULT '#{column[:default].nil? ? 'NULL' : column[:default]}'" if default
           enum = column[:type].gsub(/enum|\(|\)/, '')
           max_enum_size = enum.split(',').map{ |check| check.size() -2}.sort[-1]
    -      "character varying(#{max_enum_size}), check( #{column[:name]} in (#{enum}))"
    +      "character varying(#{max_enum_size})" #, check( #{column[:name]} in (#{enum}))"
         else
           puts "Unknown #{column.inspect}"
           column[:type].inspect

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
