### ISSUE TITLE
MySQL database to PostgreSQL schema

### ISSUE THREAD

**Issue by floux** [maxlapshin/mysql2postgres#14]
I am just running this utility for the first time. I was expecting it to put all tables from a MySQL 'database' into a newly created PostgreSQL schema with the same name as the MySQL db. But it turns out that all tables get put into the 'public' schema.

Would be nice to have the option to specify a schema, but by default I would argue it makes sense to make a new schema with the name of the MySQL database.

Best regards & thanks for this script!

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
