### ISSUE TITLE
Odd error in the middle of loading a table

### ISSUE THREAD

**Issue by mdotmoment11** [maxlapshin/mysql2postgres#17]
In the middle of loading a table, the script threw this:

Loading mat_event...
520000 of 1351268 rows loaded. [ETA: 2010/09/28 11:08 (00h:01m:52s)]mysql2psql:360:in `block in process_row': undefined method `hour' for nil:NilClass (NoMethodError)
        from mysql2psql:357:in `each'
        from mysql2psql:357:in `each_with_index'
        from mysql2psql:357:in `process_row'
        from mysql2psql:637:in `block in write_contents'
        from mysql2psql:241:in `block in paginated_read'
        from mysql2psql:237:in `upto'
        from mysql2psql:237:in `paginated_read'
        from mysql2psql:635:in `write_contents'
        from mysql2psql:692:in `block in convert'
        from mysql2psql:691:in `each'
        from mysql2psql:691:in `convert'
        from mysql2psql:750:in `<main>'

Not sure what to make of it. Line 360 of that script looks pretty straightforward. 

Thanks for the help.

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
