### ISSUE TITLE
Error with SMALLINT column and -1 value

### ISSUE THREAD

**Issue by zedzedtop** [maxlapshin/mysql2postgres#18]
in first sorry for my bad english. I hope you understand me.

In table with small int column with value set to -1, the script make record with 4294967295 value.
I have searched in source code, particularly in paginated_read function (line 232)
If i replace mysql.prepare and mysql.execute with a simple mysql.query, it's ok (i remake query for each limit).

def paginated_read(table, page_size)
    count = table.count_for_pager
    return if count < 1
    counter = 0
    0.upto((count + page_size)/page_size) do |i|
      query = table.has_id? ? 'WHERE id >= '+String(i*page_size)+' AND id < '+String(table.has_id? ? (i+1)*page_size : page_size)+'' : 'LIMIT '+String(i*page_size)+','+String(table.has_id? ? (i+1)*page_size : page_size)+''
      query = "SELECT #{table.columns.map{|c| "`"+c[:name]+"`"}.join(", ")} FROM `#{table.name}` #{query}"    
      statement = @mysql.query(query)
      while row = statement.fetch_row
        counter += 1
        yield(row, counter)
      end
    end
    counter
  end

gem --version
1.3.5

ruby --version
ruby 1.8.7 (2008-08-11 patchlevel 72) [x86_64-linux]

mysql --version
mysql  Ver 14.12 Distrib 5.0.51a, for debian-linux-gnu (x86_64) using readline 5.2

I don't understand why fetch don't return -1 value and fetch_row return -1 

Thanks
Seb

ps: sorry for my atrocious ruby code but it's the first time (read and write ruby code ...)

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
