### ISSUE TITLE
mysql year() datatype not converted and left blank.

### ISSUE THREAD

**Issue by k3mist** [maxlapshin/mysql2postgres#20]
***MYSQL DUMP:

DROP TABLE IF EXISTS `amex_quarterly_metrics`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `amex_quarterly_metrics` (
  `year` year(4) NOT NULL,
  `quarter` enum('1','2','3','4') NOT NULL,
  `chargeoffs` float DEFAULT NULL,
  `delinquency` float DEFAULT NULL,
  PRIMARY KEY (`year`,`quarter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

***POSTGRES CONVERSION:

DROP TABLE IF EXISTS "amex_quarterly_metrics" CASCADE;
 
CREATE TABLE "amex_quarterly_metrics" (
  "year" ,
  "quarter" character varying(1) check( quarter in ('1','2','3','4')) NOT NULL,
  "chargeoffs" numeric(4, 0),
  "delinquency" numeric(4, 0),
  CONSTRAINT amex_quarterly_metrics_pkey PRIMARY KEY("year", "quarter")
)
WITHOUT OIDS;

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
