### ISSUE TITLE
Can't get integration test to run

### ISSUE THREAD

**Issue by TeAmigo** [maxlapshin/mysql2postgres#23]
Probably missing something obvious here. The databases are set up as suggested in the Readme, but when I try and run the integration test, I get a series of errors, 
1) Error:
test_table_creation(ConvertToDbTest):
NameError: uninitialized class variable @@mysql2psql in ConvertToDbTest
    ./test/integration/convert_to_db_test.rb:28:in `test_table_creation'
 2) Error:
test_basic_numerics_bigint(ConvertToFileTest):
NameError: uninitialized class variable @@content in ConvertToFileTest
    ./test/integration/convert_to_file_test.rb:24:in `content'
    ./test/integration/convert_to_file_test.rb:48:in `test_basic_numerics_bigint'
and a few more. What am I missing? Thanks for any help,
Rick

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
