### ISSUE TITLE
"not an index" errors

### ISSUE THREAD

**Issue by elopio** [maxlapshin/mysql2postgres#24]
Hello,

I'm trying this script to migrate my Drupal to psql.

I ran the script, and all the tables were create. But I got two errors:

Indexing table node...
Couldn't create indexes on #<Mysql2psql::MysqlReader::Table:0x7f082e76c8b0> ([{:primary=>true, :columns=>["nid"]}, {:unique=>true, :columns=>["vid"], :name=>"vid"}, {:columns=>["changed"], :name=>"node_changed"}, {:columns=>["created"], :name=>"node_created"}, {:columns=>["moderate"], :name=>"node_moderate"}, {:columns=>["status", "type", "nid"], :name=>"node_status_type"}, {:columns=>["title", "type"], :name=>"node_title_type"}, {:columns=>["type"], :name=>"node_type"}, {:columns=>["uid"], :name=>"uid"}, {:columns=>["tnid"], :name=>"tnid"}, {:columns=>["translate"], :name=>"translate"}, {:columns=>["promote", "status", "sticky", "created"], :name=>"node_frontpage"}])
ERROR:  "node_type" is not an index
HINT:  Use DROP TABLE to remove a table.
./../lib/mysql2psql/postgres_db_writer.rb:108:in `exec'
./../lib/mysql2psql/postgres_db_writer.rb:108:in `write_indexes'
./../lib/mysql2psql/postgres_db_writer.rb:93:in `each'

Indexing table users...
Couldn't create indexes on #<Mysql2psql::MysqlReader::Table:0x7f082e76c298> ([{:primary=>true, :columns=>["uid"]}, {:unique=>true, :columns=>["name"], :name=>"name"}, {:columns=>["access"], :name=>"access"}, {:columns=>["created"], :name=>"created"}, {:columns=>["mail"], :name=>"mail"}])
ERROR:  "access" is not an index
HINT:  Use DROP TABLE to remove a table.
./../lib/mysql2psql/postgres_db_writer.rb:108:in `exec'
./../lib/mysql2psql/postgres_db_writer.rb:108:in `write_indexes'
./../lib/mysql2psql/postgres_db_writer.rb:93:in `each'

If you need more information, please let me know.

Thanks for the great work.

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
