### ISSUE TITLE
problem with conversion of mysql bit(1) to postgres boolean

### ISSUE THREAD

**Issue by yanky80** [maxlapshin/mysql2postgres#27]
Hi all:

I have tried to migrate a mysql database to postgres, and got some errors. Here is the error log:
psql:/opt/cth/data/cth20110323_data_pg.sql:756407: error:  invalid boolean type input syntax: ""
background:  COPY coordinator, row 3, col haszone: ""

I checked mysql database and the generated sql script for postgres, and found that "haszone" field is bit(1) type in mysql, bit(1) is stored as binary value in mysql, and this binary value is not written to sql script file correctly. Actually this issue is explained on "Notes, Limitations, Outstanding Issues.." section, but that tweak doesn't work for me.

If bit(1) could be converted to t/f in generated sql, that would be great.

thanks for your work.

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
