### ISSUE TITLE
missing data after migration

### ISSUE THREAD

**Issue by joewilliams** [maxlapshin/mysql2postgres#32]
Using this tool to migrate between mysql 5.1 and postgres 9.1 it seems to create all the tables properly but none of the data. In the command output I end up seeing something like:

Counting rows of invite_requests... 
Rows counted
Loading invite_requests...

 rows loaded in 0min 0s
Counting rows of org_invite_codes... 
Rows counted
Loading org_invite_codes...

Seems to suggest it didn't load any rows.

**Comment by paazmaya** [comment]
Possibly related to #31

**Comment by paazmaya** [comment]
Closing as duplicate of #31
