### ISSUE TITLE
postgres_db_writer and postgres_file_writer: same but different

### ISSUE THREAD

**Issue by apeckham** [maxlapshin/mysql2postgres#33]
Hi,

It looks like postgres_db_writer and postgres_file_writer are doing different things now:

- db writer creates indexes, and file writer ignores them:
https://github.com/maxlapshin/mysql2postgres/blob/master/lib/mysql2psql/postgres_db_writer.rb#L87:
https://github.com/maxlapshin/mysql2postgres/blob/master/lib/mysql2psql/postgres_file_writer.rb#L109

- db writer doesn't truncate, but file writer does, when the force_truncate flag is on

- db writer changes its behavior based on the Postgres version, and file writer doesn't (because it doesn't have a connection, but perhaps the user could pass a flag)

- there are a lot of duplicated SQL statements between the files

As a user I would expect the "MySQL->Postgres" and "MySQL->file->Postgres" methods to have the same result. Should we refactor to reduce duplication and the differences between the two modes?

Aaron

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
