### ISSUE TITLE
running migrations after conversion?

### ISSUE THREAD

**Issue by crankharder** [maxlapshin/mysql2postgres#37]
I've converted using file and then importing as well as directly into postgres.

After quickly poking around, I see my tables/columns are present, but running 'rake db:migrate' wants to run every migration in my app.

There are two odd things about this:

1) It's as if the mySQL table schema_migrations didn't get converted to however postgres manages schema state.

2) rake db:migrate -- about half of my migrations run fine.  This is incredibly odd my first migration creates the "events" table, but that table already exists -- postgres doesn't blow up on that?

Anyways, I would expect that db:migrate would have to do nothing after converting the DBs -- did I skip something?

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments against the `master` branch.
