### ISSUE TITLE
Transfer ownership or add collaborators?

### ISSUE THREAD

**Issue by apeckham** [maxlapshin/mysql2postgres#38]
mysql2postgres is awesome, but the primary repo has many unresolved issues and merge requests. We'd love to close some of these and consolidate the work being done on forks.

Max, if you don't have time, will you add someone to collaborators, or transfer ownership to someone who can review the new changes?

Thanks,

Aaron

**Comment by n-rodriguez** [comment]
> Ok, who is going to be added to collaborators?

Hi there! Any news?

**Comment by maxlapshin** [comment]
Wow, somebody is still using mysql? =)

Ok, who is going to join?

**Comment by n-rodriguez** [comment]
> Ok, who is going to join?

well... me :)

**Comment by n-rodriguez** [comment]
@maxlapshin thank you!
