### ISSUE TITLE
Error migrating moodle: syntax error in or next to "DEFAULT" (PGError)

### ISSUE THREAD

**Issue by leleobhz** [maxlapshin/mysql2postgres#4]
Creating table moodleenrol_authorize...
Error: 
CREATE TABLE "moodleenrol_authorize" (
  "id" integer DEFAULT nextval('moodleenrol_authorize_id_seq'::regclass) NOT NULL,
  "paymentmethod" character varying(6), check( paymentmethod in ('cc','echeck')) DEFAULT cc NOT NULL,
  "refundinfo" integer DEFAULT 0 NOT NULL,
  "ccname" character varying(255) NOT NULL,
  "courseid" bigint DEFAULT 0 NOT NULL,
  "userid" bigint DEFAULT 0 NOT NULL,
  "transid" bigint DEFAULT 0 NOT NULL,
  "status" bigint DEFAULT 0 NOT NULL,
  "timecreated" bigint DEFAULT 0 NOT NULL,
  "settletime" bigint DEFAULT 0 NOT NULL,
  "amount" character varying(10) NOT NULL,
  "currency" character(3) DEFAULT 'USD'::char NOT NULL
)
WITHOUT OIDS;
./mysql2psql:466:in `exec': ERRO:  erro de sintaxe em ou próximo a "DEFAULT" (PGError)
LINE 3: ...ying(6), check( paymentmethod in ('cc','echeck')) DEFAULT cc...
                                                             ^
	from ./mysql2psql:466:in `write_table'
	from ./mysql2psql:617:in `convert'
	from ./mysql2psql:616:in `each'
	from ./mysql2psql:616:in `convert'
	from ./mysql2psql:682

And the process die.

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments aganst the `master` branch.
