### ISSUE TITLE
Couldn't create indexes / undefined method "parse_csv"

### ISSUE THREAD

**Issue by forthrin** [maxlapshin/mysql2postgres#42]
The following error occurs when trying to convert InnoDB tables with foreign keys.

Couldn't create indexes on #<Mysql2psql::MysqlReader::Table:0x10118db28> ([{:primary=>true, :columns=>["id"]}, {:columns=>["rr"], :name=>"rr"}])
undefined method `parse_csv' for "rr":String
/Library/Ruby/Gems/1.8/../mysql2psql/mysql_reader.rb:110:in "load_indexes"
/Library/Ruby/Gems/1.8/../mysql2psql/mysql_reader.rb:105:in "each"
/Library/Ruby/Gems/1.8/../mysql2psql/mysql_reader.rb:105:in "load_indexes"

The foreign key is defined as follows:

constraint "rr" foreign key ("rr") references "other" ("id") on delete cascade on update cascade

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments against the `master` branch.
