### ISSUE TITLE
UTF8 data not migrating correctly

### ISSUE THREAD

**Issue by emarthinsen** [maxlapshin/mysql2postgres#49]
I'm finding that utf8 data that is present in my source database (confirmed via the mysql command-line client) des not end up encoded correctly in the destination database (confirmed with psql). In both the yml configuration blocks for my source and destination databases, I have:

encoding: utf8

Also, I confirmed that the character encodings on both the source and destination databases are utf8.

Any ideas what the fix might be?

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments against the `master` branch.
