### ISSUE TITLE
how to configure 

### ISSUE THREAD

**Issue by alfredpl** [maxlapshin/mysql2postgres#53]
i installed but executing mysql-to-postgres getting following error 

sysadmin@system8:~/mysql2postgres$ mysql-to-postgres 
/var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:33:in `block in setup': You have already activated pg 0.9.0, but your Gemfile requires pg 0.17.0. Using bundle exec may solve this. (Gem::LoadError)
	from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:19:in `setup'
	from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:120:in `setup'
	from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/setup.rb:7:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:59:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
	from /var/lib/gems/1.9.1/gems/mysql2psql-0.1.0/bin/mysql-to-postgres:5:in `<top (required)>'
	from /usr/local/bin/mysql-to-postgres:19:in `load'
	from /usr/local/bin/mysql-to-postgres:19:in `<main>'

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments against the `master` branch.
