### ISSUE TITLE
RuntimeError: `<top (required)>': '' does not exist

### ISSUE THREAD

**Issue by iby** [maxlapshin/mysql2postgres#65]
I am trying to get the `mysqltopostgres` command to work for the second day without any luck. I am using the latest 0.2.19 version from the master branch. I suspect I'm doing something wrong, do you know what that might be?

``` bash
$ mysqltopostgres
/usr/local/var/rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1/gems/mysqltopostgres-0.2.19/bin/mysqltopostgres:30:in `<top (required)>': '' does not exist (RuntimeError)
    from /usr/local/var/rbenv/versions/1.9.3-p550/bin/mysqltopostgres:23:in `load'
    from /usr/local/var/rbenv/versions/1.9.3-p550/bin/mysqltopostgres:23:in `<main>'
$ gem list

*** LOCAL GEMS ***

activemodel (4.1.7)
activerecord (4.1.7)
activesupport (4.1.7)
addressable (2.3.6)
arel (5.0.1.20140414130214)
bigdecimal (1.2.5, 1.1.0)
builder (3.2.2)
bundler (1.7.4)
descendants_tracker (0.0.4)
faraday (0.9.0)
git (1.2.8)
github_api (0.12.2)
hashie (3.3.1)
highline (1.6.21)
i18n (0.6.11)
io-console (0.4.2, 0.3)
jeweler (2.0.1)
json (1.8.1, 1.5.5)
jwt (1.0.0)
mini_portile (0.6.0)
minitest (5.4.2, 2.5.1)
multi_json (1.10.1)
multi_xml (0.5.5)
multipart-post (2.0.0)
mysql-pr (2.9.11)
mysqltopostgres (0.2.19)
nokogiri (1.6.3.1)
oauth2 (1.0.0)
pg (0.17.1)
postgres-pr (0.6.3)
power_assert (0.1.4)
rack (1.5.2)
rake (10.3.2, 0.9.2.2)
rdoc (4.1.2, 3.9.5)
test-unit (3.0.3)
thread_safe (0.3.4)
tzinfo (1.2.2)
$ ruby -v
ruby 1.9.3p550 (2014-10-27 revision 48165) [x86_64-darwin14.0.0]
```

**Comment by hmcmanus** [comment]
Hey everyone,

I'm also getting this issue

mysqltopostgres:30:in `<top (required)>': '' does not exist (RuntimeError)

Did anyone above find the resolution to this? I'm running this on a RedHat machine with the following bundle:

bundle list
Gems included by the bundle:
  * activemodel (3.2.22)
  * activerecord (3.2.22)
  * activesupport (3.2.22)
  * arel (3.0.3)
  * builder (3.0.4)
  * bundler (1.10.6)
  * i18n (0.7.0)
  * multi_json (1.11.2)
  * mysql-pr (2.9.11)
  * mysqltopostgres (0.2.20)
  * pg (0.18.3)
  * postgres-pr (0.7.0)
  * test-unit (2.5.5)
  * tzinfo (0.3.44)

Any help would be appreciated.

**Comment by hmcmanus** [comment]
Just in case someone else got this error, I got it by not following the command line usage:

The configuration yaml file should be the first argument when mysqltopostgres is called. 

My question now is how to connect to a database which is not running locally? Is this possible without specifying a socket file?

**Comment by JohnMerlino2** [comment]
@maxlapshin I assume the only reason why the OP was using this gem is because somehow it is in the Heroku documentation for migrating from MySQL to PostgreSQL. But seeing that this shit is unmaintained and the owner is disillusioned I blame Heroku for even referencing this. In addition to being disilusioned, the owner is also hotheaded, perhaps because he is frustrated with American men coming to Russia and taking his girlfriends.
