### ISSUE TITLE
 cannot load such file -- mysqltopostgres

### ISSUE THREAD

**Issue by jianfengye** [maxlapshin/mysql2postgres#70]
i got the error here:

[root@localhost mysql2postgres]# mysqltopostgres
WARN: Unresolved specs during Gem::Specification.reset:
      test-unit (>= 2.1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/rvm/gems/ruby-2.1.2/gems/mysqltopostgres-0.2.15/bin/mysqltopostgres:7:in `require': cannot load such file -- mysqltopostgres (LoadError)
	from /usr/local/rvm/gems/ruby-2.1.2/gems/mysqltopostgres-0.2.15/bin/mysqltopostgres:7:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/mysqltopostgres:23:in `load'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/mysqltopostgres:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by paazmaya** [comment]
Similar to #66, need to make new release

**Comment by sean-perryman** [comment]
No progress on this yet?

**Comment by paazmaya** [comment]
Sorry, no new release yet, as I haven't had the time to take a look at the procedure and how to contain only the "good" fixes

**Comment by MagNetCZ** [comment]
I have the very same problem after building the gem from git. Tried in multiple ruby versions both virtual and system installed (1.9.3, 2.1.2, 2.2.0).

Can I somehow edit the environment to make it run?
I want to migrate a rails app MySQL DB to Postgres and this is the recommended tool by Heroku.

**Comment by alex-marmot** [comment]
I still got the same problem..
