### ISSUE TITLE
You have already activated postgres-pr 0.6.3

### ISSUE THREAD

**Issue by hellojere** [maxlapshin/mysql2postgres#78]
Trying to set this up on a fresh virtual machine, but facing the following error:  

    You have already activated postgres-pr 0.6.3, but your Gemfile requires postgres-pr 0.7.0. Prepending 'bundle exec' to your command may solve this. 

I'm familiar working with rbenv & bundler on Rails to avoid these issues, but can't seem to get around this. Any help highly appreciated.

**Comment by jfeust** [comment]
Also having the same issue after following the install instructions.

**Comment by michballard** [comment]
I am also having this exact issue

**Comment by rmserp12** [comment]
+1 same

**Comment by nicolas-besnard** [comment]
+1

**Comment by jgrancher** [comment]
+1

**Comment by paazmaya** [comment]
Would anyone care to try if d2d922fae1b2f99ef6298f89e5eafe73e682648d made any difference?

**Comment by nicolas-besnard** [comment]
Still failing
![screen shot 2015-08-28 at 10 17 27](https://cloud.githubusercontent.com/assets/1261670/9542081/07fa1ae6-4d6e-11e5-8b91-94fbd7e72f32.png)

**Comment by nicolas-besnard** [comment]
Works for me !

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments against the `master` branch.
