### ISSUE TITLE
Installation issue: You have already activated builder 3.0.4, but your Gemfile requires builder 3.2.2.

### ISSUE THREAD

**Issue by hellorico** [maxlapshin/mysql2postgres#81]
Hello,

I am stuck with this installation issue.
When I do `gem install mysqltopostgres`, the wrong version of gem builder is installed and then the first call to the function gives me this error:

`ubuntu@ubuntu-amd64:~/mysql2postgres$ mysqltopostgres`
`/home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:34:in 'block in setup': You have already activated builder 3.0.4, but your Gemfile requires builder 3.2.2. Prepending 'bundle exec' to your command may solve this. (Gem::LoadError)`
`from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:19:in 'setup'`
`from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler.rb:121:in 'setup'`
`from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/setup.rb:7:in '<top (required)>'`
`from /home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in 'require'`
`from /home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in 'require'`
`from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/mysqltopostgres-0.2.20/bin/mysqltopostgres:5:in '<top (required)>'`
`from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/mysqltopostgres:23:in 'load'`
`from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/mysqltopostgres:23:in '<main>'`
`from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in 'eval'`
`from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in '<main>'`

If I remove the builder 3.0.4 with gem uninstall builder, the system will complain as well with this error:  `Could not find 'builder' (~> 3.0.0) - did find: [builder-3.2.2]`

Thank you for your help

Eric

**Comment by mandeepbal** [comment]
+1

**Comment by pekindenis** [comment]
+1, with Ubuntu Linux.

/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:33:in `block in setup': You have already activated builder 3.0.4, but your Gemfile requires builder 3.2.2. Using bundle exec may solve this. (Gem::LoadError)
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:19:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:120:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:7:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/mysqltopostgres-0.2.20/bin/mysqltopostgres:5:in `<top (required)>'
	from /usr/local/bin/mysqltopostgres:23:in `load'
	from /usr/local/bin/mysqltopostgres:23:in `<main>'

**Comment by iwz** [comment]
Also getting the same error.

**Comment by mantagen** [comment]
+1 on Ubuntu

```
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:33:in `block in setup': You have already activated builder 3.0.4, but your Gemfile requires builder 3.2.2. Using bundle exec may solve this. (Gem::LoadError)
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:19:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:120:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:7:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/mysqltopostgres-0.2.20/bin/mysqltopostgres:5:in `<top (required)>'
	from /usr/local/bin/mysqltopostgres:23:in `load'
	from /usr/local/bin/mysqltopostgres:23:in `<main>'
```

**Comment by lukecyca** [comment]
Same issue on CentOS 6 with Ruby 1.9.3

**Comment by DimasInchidi** [comment]
same issue ubuntu 14.04 LTS
```
/var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:34:in `block in setup': You have already activated builder 3.0.4, but your Gemfile requires builder 3.2.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:19:in `setup'
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/setup.rb:8:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
	from /var/lib/gems/1.9.1/gems/mysqltopostgres-0.2.20/bin/mysqltopostgres:5:in `<top (required)>'
	from /usr/local/bin/mysqltopostgres:23:in `load'
	from /usr/local/bin/mysqltopostgres:23:in `<main>'

```

**Comment by soychicka** [comment]
+1, OS X Yosemite/Ruby 1.9.3 via rvm

    You have already activated builder 3.0.4, but your Gemfile requires builder 3.2.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /Users/soychicka/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.6/lib/bundler/runtime.rb:19:in `setup'
	from /Users/soychicka/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
	from /Users/soychicka/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.6/lib/bundler/setup.rb:8:in `<top (required)>'
	from /Users/soychicka/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/soychicka/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/soychicka/.rvm/gems/ruby-1.9.3-p551/gems/mysqltopostgres-0.2.20/bin/mysqltopostgres:5:in `<top (required)>'
	from /Users/soychicka/.rvm/gems/ruby-1.9.3-p551/bin/mysqltopostgres:23:in `load'
	from /Users/soychicka/.rvm/gems/ruby-1.9.3-p551/bin/mysqltopostgres:23:in `<main>'
	from /Users/soychicka/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /Users/soychicka/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

**Comment by paazmaya** [comment]
Can you please try to build it from `master` and see if the error is gone?

**Comment by soychicka** [comment]
ruby '1.9.3'
source 'https://rubygems.org'
gem "builder", '3.0.4'
gem 'rake', '~> 10.3'
gem 'mysql-pr', '~> 2.9'
gem 'postgres-pr', '~> 0.6'

platforms :jruby do
  gem 'activerecord'
  gem 'jdbc-postgres'
  gem 'activerecord-jdbc-adapter'
  gem 'activerecord-jdbcpostgresql-adapter'
end

platforms :mri do
  gem 'pg', '~> 0.17'
end

gem 'test-unit',  '2.5.5'

group :test do
  gem 'jeweler', '~> 2.0'
end

**Comment by brchristian** [comment]
@paazmaya FWIW I was just able to install cleanly on Ubuntu 14.04 from `master`.

**Comment by paazmaya** [comment]
Thank you!

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments against the `master` branch.

**Comment by Willgg** [comment]
Hi, I use ubuntu and tried to build from master. I got this error after running $ mysqltoposgres: /home/william/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pg-0.20.0/lib/pg/connection.rb:270: warning: already initialized constant PGconn
/home/william/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/postgres-pr-0.7.0/lib/postgres-pr/postgres-compat.rb:6: warning: previous definition of PGconn was here
/home/william/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pg-0.20.0/lib/pg/result.rb:34: warning: already initialized constant PGresult
/home/william/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/postgres-pr-0.7.0/lib/postgres-pr/postgres-compat.rb:69: warning: previous definition of PGresult was here
./bin/mysqltopostgres:30:in `<main>': '' does not exist (RuntimeError)
