### ISSUE TITLE
Cannot dump the db entirely

### ISSUE THREAD

**Issue by degva** [maxlapshin/mysql2postgres#84]
Hello, 
I'm having some issues. I'm using mariadb instead of mysql.
The conversion creates only part of the database sql before it hits this error:

Mysql2psql: Conversion failed: uninitialized constant Mysql2psql::MysqlReader::Mysql
uninitialized constant Mysql2psql::MysqlReader::Mysql

**Comment by paazmaya** [comment]
Can you please try with `master` branch version and then post the results, with the information about the versions you are using?

**Comment by paazmaya** [comment]
Closing as an old issue, that would seem to be out of date.
Feel free to re-open and update with comments against the `master` branch.
