### ISSUE TITLE
Publishing to RubyGems

### ISSUE THREAD

**Issue by paazmaya** [maxlapshin/mysql2postgres#85]
Seems that there are several of the same:
- https://rubygems.org/gems/mysql2psql
  - Owned by @maxlapshin 
  - Only version `0.1.0` (September 18, 2010)
- https://rubygems.org/gems/mysql-to-postgres
  - Owned by @ajokela 
  - Three versions, latest `0.2.14` (August 10, 2012)
- https://rubygems.org/gems/mysqltopostgres
  - Owned by @ajokela 
  - Only version `0.2.15` (August 20, 2012)

And while I tried to publish `mysqltopostgres`, failed since I have no permission.

Any chance @ajokela or @maxlapshin to change that?

**Comment by ajokela** [comment]
@paazmaya you're asking to be made owner of one of the gems?

**Comment by paazmaya** [comment]
@ajokela that would solve the publishing trouble..

**Comment by maxlapshin** [comment]
@paazmaya  Let's find the way to give you access

**Comment by paazmaya** [comment]
@maxlapshin thank you!

**Comment by paazmaya** [comment]
Closing at something that does not go forward.

**Comment by sobrinho** [comment]
The latest two aren't released anymore and the first one is still an old version.

@paazmaya any news on that?

**Comment by paazmaya** [comment]
@sobrinho I never received the required access and have since lost interest in this project.

**Comment by sobrinho** [comment]
Okay, thanks! <3

**Comment by maxlapshin** [comment]
Whom should I add required rights?

**Comment by n-rodriguez** [comment]
> Whom should I add required rights?

Me? :)
