### ISSUE TITLE
Which version is the working one?

### ISSUE THREAD

**Issue by cimm** [maxlapshin/mysql2postgres#86]
- I tried the installation instructions in the README... no go.
- I tried downloading the version from RubyGems... no go.

Is there a version that works which can be used? Thank you.

**Comment by paazmaya** [comment]
The `master` branch should be "working" but cannot say anything else without further information.

**Comment by paazmaya** [comment]
Related to #85

**Comment by cimm** [comment]
Used the fork from GitLab which did the trick: https://github.com/gitlabhq/mysql-postgresql-converter
