### ISSUE TITLE
create sequence : watch out table name that contain caps

### ISSUE THREAD

**Issue by askalia** [maxlapshin/mysql2postgres#92]
Because PG is case sensitive, 
in CREATE SEQUENCE statement , the table name next to FROM instruction should be surrounded by double-quotes, so as to take care of table names case sensitive.
Thanks

**Comment by paazmaya** [comment]
PR with test case warmly welcome 😍

**Comment by askalia** [comment]
sorry wrong project, thus you have no problem with "create sequence".
Have a good day.
