### ISSUE TITLE
Wrong key "hostname" in documentation

### ISSUE THREAD

**Issue by raiblue** [maxlapshin/mysql2postgres#98]
Given example in README.md, mysql source section:
```yaml
mysql_data_source: &pii
  hostname: localhost
```
But there is no "hostname" key there actually, it must be "host". When hostname is used it has no effect and default value for host key is taken (localhost and unix socket usage).
 
You can fix the example as:
```yaml
mysql_data_source: &pii
  host: localhost
```

**Comment by pushamaku** [comment]
Thank you!
